/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests/test_math.ts" instead.
 */

#include <check.h>

#line 1 "tests/test_math.ts"
#include <math.h>
#include <stdlib.h>

#include "../s21_math.h"

/*--------EXP-TEST-START------------------------------------------*/

START_TEST(exp_test_1) {
#line 8
  double a = 4;
  long double res1 = exp(a);
  long double res2 = s21_exp(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(exp_test_2) {
#line 14
  double a = -4;
  long double res1 = exp(a);
  long double res2 = s21_exp(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(exp_test_3) {
#line 20
  double a = +0;
  long double res1 = exp(a);
  long double res2 = s21_exp(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(exp_test_4) {
#line 26
  double a = -0;
  long double res1 = exp(a);
  long double res2 = s21_exp(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(exp_test_5) {
#line 32
  double a = 123456789;
  long double res2 = s21_exp(a);
  ck_assert_ldouble_infinite(res2);
}
END_TEST

START_TEST(exp_test_6) {
#line 37
  double a = 1024;
  long double res2 = s21_exp(a);
  ck_assert_ldouble_infinite(res2);
}
END_TEST

START_TEST(exp_test_7) {
#line 42
  double a = -1024;
  long double res1 = exp(a);
  long double res2 = s21_exp(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(exp_test_8) {
#line 48
  long double res2 = s21_exp(S21_NAN);
  ck_assert_ldouble_nan(res2);

  /*--------EXP-TEST-END------------------------------------------*/

  /*--------ACOS-TEST-START---------------------------------------*/
}
END_TEST

START_TEST(acos_test_1) {
#line 57
  double a = 4;
  long double res2 = s21_acos(a);
  ck_assert_ldouble_nan(res2);
}
END_TEST

START_TEST(acos_test_2) {
#line 62
  double a = -4;
  long double res2 = s21_acos(a);
  ck_assert_ldouble_nan(res2);
}
END_TEST

START_TEST(acos_test_3) {
#line 67
  double a = +0;
  long double res1 = acos(a);
  long double res2 = s21_acos(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(acos_test_4) {
#line 73
  double a = -0;
  long double res1 = acos(a);
  long double res2 = s21_acos(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(acos_test_5) {
#line 79
  double a = 123456789;
  long double res2 = s21_acos(a);
  ck_assert_ldouble_nan(res2);
}
END_TEST

START_TEST(acos_test_6) {
#line 84
  double a = 111;
  long double res2 = s21_acos(a);
  ck_assert_ldouble_nan(res2);
}
END_TEST

START_TEST(acos_test_7) {
#line 89
  double a = -0.4;
  long double res1 = acos(a);
  long double res2 = s21_acos(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(acos_test_8) {
#line 95
  double a = 0.1;
  long double res1 = acos(a);
  long double res2 = s21_acos(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(acos_test_9) {
#line 101
  double a = 0.1473433;
  long double res1 = acos(a);
  long double res2 = s21_acos(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(acos_test_10) {
#line 107
  double a = -0.5473433;
  long double res1 = acos(a);
  long double res2 = s21_acos(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(acos_test_11) {
#line 113
  double a = -0.5473433;
  long double res1 = acos(a);
  long double res2 = s21_acos(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(acos_test_12) {
#line 119
  double a = -884848584.5473433;
  long double res2 = s21_acos(a);
  ck_assert_ldouble_nan(res2);
}
END_TEST

START_TEST(acos_test_13) {
#line 124
  long double res2 = s21_acos(S21_NAN);
  ck_assert_ldouble_nan(res2);
}
END_TEST

START_TEST(acos_test_14) {
#line 128
  long double res2 = s21_acos(S21_POS_INF);
  ck_assert_ldouble_infinite(res2);
  /*--------ACOS-TEST-END-----------------------------------------*/

  /*--------POW-TEST-START---------------------------------------*/
}
END_TEST

START_TEST(pow_test_1) {
#line 135
  double a = 4.12;
  long double res1 = pow(a, 3.1254);
  long double res2 = s21_pow(a, 3.1254);
  long double res = res2 - res1;
  ck_assert_ldouble_lt(res, 0.000001);
}
END_TEST

START_TEST(pow_test_2) {
#line 143
  double a = -4;
  long double res1 = pow(a, 16);
  long double res2 = s21_pow(a, 16);
  long double res = res2 - res1;
  ck_assert_ldouble_lt(res, 0.000001);
}
END_TEST

START_TEST(pow_test_3) {
#line 151
  double a = +0;
  long double res1 = pow(a, 3);
  long double res2 = s21_pow(a, 3);
  long double res = res2 - res1;
  ck_assert_ldouble_lt(res, 0.000001);
}
END_TEST

START_TEST(pow_test_4) {
#line 159
  double a = -84.24;
  long double res2 = s21_pow(a, 8.954);
  ck_assert_ldouble_nan(res2);
}
END_TEST

START_TEST(pow_test_5) {
#line 164
  double a = 84.24;
  long double res1 = pow(a, 9);
  long double res2 = s21_pow(a, 9);
  long double res = res2 - res1;
  ck_assert_ldouble_lt(res, 0.000001);
}
END_TEST

START_TEST(pow_test_6) {
#line 171
  long double res1 = s21_pow(S21_NAN, 2);
  ck_assert_ldouble_ne(res1, res1);
}
END_TEST

START_TEST(pow_test_7) {
#line 175
  double a = -104.987;
  long double res2 = s21_pow(a, 0.98);
  ck_assert_ldouble_nan(res2);
}
END_TEST

START_TEST(pow_test_8) {
#line 180
  long double res2 = s21_pow(0, -0.98);
  ck_assert_ldouble_infinite(res2);
}
END_TEST

START_TEST(pow_test_9) {
#line 184
  double a = 84.24;
  long double res1 = pow(a, -2);
  long double res2 = s21_pow(a, -2);
  long double res = res2 - res1;
  ck_assert_ldouble_lt(res, 0.000001);
}
END_TEST

START_TEST(pow_test_10) {
#line 191
  double a = 84.24;
  long double res1 = pow(a, 0);
  long double res2 = s21_pow(a, 0);
  long double res = res2 - res1;
  ck_assert_ldouble_lt(res, 0.000001);
}
END_TEST

START_TEST(pow_test_11) {
#line 198
  double a = 0;
  long double res1 = pow(a, 0);
  long double res2 = s21_pow(a, 0);
  long double res = res2 - res1;
  ck_assert_ldouble_lt(res, 0.000001);

  /*--------POW-TEST-END-----------------------------------------*/

  /*------------ABS-TEST-START-----------------------------------------*/
}
END_TEST

START_TEST(abs_test_1) {
#line 209
  int a = -43434314;
  int res1 = abs(a);
  int res2 = s21_abs(a);
  ck_assert_int_eq(res1, res2);
}
END_TEST

START_TEST(abs_test_2) {
#line 215
  int a = -4;
  int res1 = abs(a);
  int res2 = s21_abs(a);
  ck_assert_int_eq(res1, res2);
}
END_TEST

START_TEST(abs_test_3) {
#line 221
  int a = +0;
  int res1 = abs(a);
  int res2 = s21_abs(a);
  ck_assert_int_eq(res1, res2);
}
END_TEST

START_TEST(abs_test_4) {
#line 227
  int a = -0;
  int res1 = abs(a);
  int res2 = s21_abs(a);
  ck_assert_int_eq(res1, res2);
}
END_TEST

START_TEST(abs_test_5) {
#line 233
  int a = 123456789;
  int res1 = abs(a);
  int res2 = s21_abs(a);
  ck_assert_int_eq(res1, res2);
}
END_TEST

START_TEST(abs_test_6) {
#line 239
  int a = -1;
  int res1 = abs(a);
  int res2 = s21_abs(a);
  ck_assert_int_eq(res1, res2);
}
END_TEST

START_TEST(abs_test_7) {
#line 245
  int a = -1024;
  int res1 = abs(a);
  int res2 = s21_abs(a);
  ck_assert_int_eq(res1, res2);
}
END_TEST

START_TEST(abs_test_8) {
#line 251
  int a = -9126789;
  int res1 = abs(a);
  int res2 = s21_abs(a);
  ck_assert_int_eq(res1, res2);

  /*--------ABS-TEST-END-----------------------------------------*/

  /*--------FLOOR-TEST-START-----------------------------------------*/
}
END_TEST

START_TEST(floor_test_1) {
#line 261
  long double a = 4.122232134343;
  long double res1 = floor(a);
  long double res2 = s21_floor(a);
  ck_assert_ldouble_eq(res1, res2);
}
END_TEST

START_TEST(floor_test_2) {
#line 267
  long double a = -4.345532335343;
  long double res1 = floor(a);
  long double res2 = s21_floor(a);
  ck_assert_ldouble_eq(res1, res2);
}
END_TEST

START_TEST(floor_test_3) {
#line 273
  long double a = +0.234343433;
  long double res1 = floor(a);
  long double res2 = s21_floor(a);
  ck_assert_ldouble_eq(res1, res2);
}
END_TEST

START_TEST(floor_test_4) {
#line 279
  long double a = -0.243232;
  long double res1 = floor(a);
  long double res2 = s21_floor(a);
  ck_assert_ldouble_eq(res1, res2);
}
END_TEST

START_TEST(floor_test_5) {
#line 285
  long double a = 121212.123456789;
  long double res1 = floor(a);
  long double res2 = s21_floor(a);
  ck_assert_ldouble_eq(res1, res2);
}
END_TEST

START_TEST(floor_test_6) {
#line 291
  long double a = 453.1024;
  long double res1 = floor(a);
  long double res2 = s21_floor(a);
  ck_assert_ldouble_eq(res1, res2);
}
END_TEST

START_TEST(floor_test_7) {
#line 297
  long double a = -1024.12;
  long double res1 = floor(a);
  long double res2 = s21_floor(a);
  ck_assert_ldouble_eq(res1, res2);
}
END_TEST

START_TEST(floor_test_8) {
#line 303
  long double a = -123456789;
  long double res1 = floor(a);
  long double res2 = s21_floor(a);
  ck_assert_ldouble_eq(res1, res2);

  /*--------FLOOR-TEST-END-----------------------------------------*/

  /*--------FABS-TEST-START-----------------------------------------*/
}
END_TEST

START_TEST(fabs_test_1) {
#line 312
  long double a = 4.122232134343;
  long double res1 = fabsl(a);
  long double res2 = s21_fabs(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(fabs_test_2) {
#line 318
  long double a = -4.345532335343;
  long double res1 = fabsl(a);
  long double res2 = s21_fabs(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(fabs_test_3) {
#line 324
  long double a = +0.234343433;
  long double res1 = fabsl(a);
  long double res2 = s21_fabs(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(fabs_test_4) {
#line 330
  long double a = -0.243232;
  long double res1 = fabsl(a);
  long double res2 = s21_fabs(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(fabs_test_5) {
#line 336
  long double a = 121212.123456789;
  long double res1 = fabsl(a);
  long double res2 = s21_fabs(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(fabs_test_6) {
#line 342
  long double a = -453.1024;
  long double res1 = fabsl(a);
  long double res2 = s21_fabs(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(fabs_test_7) {
#line 348
  long double a = -1024.12;
  long double res1 = fabsl(a);
  long double res2 = s21_fabs(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(fabs_test_8) {
#line 354
  long double a = -123456789;
  long double res1 = fabsl(a);
  long double res2 = s21_fabs(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);

  /*--------FABS-TEST-END-----------------------------------------*/

  /*--------CEIL-TEST-START-----------------------------------------*/
}
END_TEST

START_TEST(ceil_test_1) {
#line 364
  long double a = 4.122232134343;
  long double res1 = ceil(a);
  long double res2 = s21_ceil(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(ceil_test_2) {
#line 370
  long double a = -4.345532335343;
  long double res1 = ceil(a);
  long double res2 = s21_ceil(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(ceil_test_3) {
#line 376
  long double a = +0.234343433;
  long double res1 = ceil(a);
  long double res2 = s21_ceil(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(ceil_test_4) {
#line 382
  long double a = -0.243232;
  long double res1 = ceil(a);
  long double res2 = s21_ceil(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(ceil_test_5) {
#line 388
  long double a = -121212.123456789;
  long double res1 = ceil(a);
  long double res2 = s21_ceil(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(ceil_test_6) {
#line 394
  long double a = -453.1024;
  long double res1 = ceil(a);
  long double res2 = s21_ceil(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(ceil_test_7) {
#line 400
  long double a = 1024.12;
  long double res1 = ceil(a);
  long double res2 = s21_ceil(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(ceil_test_8) {
#line 406
  long double a = -123456789.54343;
  long double res1 = ceil(a);
  long double res2 = s21_ceil(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(ceil_test_9) {
#line 412
  long double a = 23456789.123432;
  long double res1 = ceil(a);
  long double res2 = s21_ceil(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(ceil_test_10) {
#line 418
  long double res2 = s21_ceil(S21_POS_INF);
  ck_assert_ldouble_infinite(res2);

  /*--------CEIL-TEST-END-----------------------------------------*/

  /*--------SIN-TEST-START-----------------------------------------*/
}
END_TEST

START_TEST(sin_test_1) {
#line 426
  long double a = 4.122232134343;
  long double res1 = sin(a);
  long double res2 = s21_sin(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(sin_test_2) {
#line 432
  long double a = -4.345532335343;
  long double res1 = sin(a);
  long double res2 = s21_sin(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(sin_test_3) {
#line 438
  long double a = +0.234343433;
  long double res1 = sin(a);
  long double res2 = s21_sin(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(sin_test_4) {
#line 444
  long double a = -0.243232;
  long double res1 = sin(a);
  long double res2 = s21_sin(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(sin_test_5) {
#line 450
  long double a = 121212.123456789;
  long double res1 = sin(a);
  long double res2 = s21_sin(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(sin_test_6) {
#line 456
  long double a = -453.1024;
  long double res1 = sin(a);
  long double res2 = s21_sin(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(sin_test_7) {
#line 462
  long double a = 1024.12;
  long double res1 = sin(a);
  long double res2 = s21_sin(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(sin_test_8) {
#line 468
  long double a = -123456789;
  long double res1 = sin(a);
  long double res2 = s21_sin(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(sin_test_9) {
#line 474
  long double a = 0.193247;
  long double res1 = sin(a);
  long double res2 = s21_sin(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(sin_test_10) {
#line 480
  long double a = 0.993247;
  long double res1 = sin(a);
  long double res2 = s21_sin(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(sin_test_11) {
#line 486
  long double res2 = s21_sin(S21_NAN);
  ck_assert_ldouble_nan(res2);

  /*--------SIN-TEST-END-----------------------------------------*/

  /*--------COS-TEST-START-----------------------------------------*/
}
END_TEST

START_TEST(cos_test_1) {
#line 495
  long double a = 4.122232134343;
  long double res1 = cos(a);
  long double res2 = s21_cos(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(cos_test_2) {
#line 501
  long double a = -4.345532335343;
  long double res1 = cos(a);
  long double res2 = s21_cos(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(cos_test_3) {
#line 507
  long double a = +0.234343433;
  long double res1 = cos(a);
  long double res2 = s21_cos(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(cos_test_4) {
#line 513
  long double a = -0.243232;
  long double res1 = cos(a);
  long double res2 = s21_cos(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(cos_test_5) {
#line 519
  long double a = 121212.123456789;
  long double res1 = cos(a);
  long double res2 = s21_cos(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(cos_test_6) {
#line 525
  long double a = -453.1024;
  long double res1 = cos(a);
  long double res2 = s21_cos(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(cos_test_7) {
#line 531
  long double a = 1024.9493912;
  long double res1 = cos(a);
  long double res2 = s21_cos(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(cos_test_8) {
#line 537
  long double a = -123456;
  long double res1 = cos(a);
  long double res2 = s21_cos(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(cos_test_9) {
#line 543
  long double a = -9459456789.1;
  long double res1 = cos(a);
  long double res2 = s21_cos(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(cos_test_10) {
#line 549
  long double a = S21_POS_INF;
  long double res2 = s21_cos(a);
  ck_assert_ldouble_nan(res2);
}
END_TEST

START_TEST(cos_test_11) {
#line 554
  long double a = S21_NEG_INF;
  long double res2 = s21_cos(a);
  ck_assert_ldouble_nan(res2);
}
END_TEST

START_TEST(cos_test_12) {
#line 559
  long double a = S21_NAN;
  long double res2 = s21_cos(a);
  ck_assert_ldouble_nan(res2);

  /*--------FMOD-TEST-END-----------------------------------------*/
}
END_TEST

START_TEST(fmod_test_1) {
#line 566
  long double a = 4.122232134343;
  long double y = 2.12;
  long double res1 = fmod(a, y);
  long double res2 = s21_fmod(a, y);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(fmod_test_2) {
#line 573
  long double a = -4.345532335343;
  long double y = 65353;
  long double res1 = fmod(a, y);
  long double res2 = s21_fmod(a, y);
  ck_assert_ldouble_eq(res1, res2);
}
END_TEST

START_TEST(fmod_test_3) {
#line 580
  long double a = +0.234343433;
  long double y = 9.99;
  long double res1 = fmod(a, y);
  long double res2 = s21_fmod(a, y);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(fmod_test_4) {
#line 587
  long double a = -0.243232;
  long double y = 0.485987479;
  long double res1 = fmod(a, y);
  long double res2 = s21_fmod(a, y);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(fmod_test_5) {
#line 594
  long double a = 121212.123456789;
  long double y = 212;
  long double res1 = fmod(a, y);
  long double res2 = s21_fmod(a, y);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(fmod_test_6) {
#line 601
  long double a = -453.1024;
  long double y = S21_PI;
  long double res1 = fmod(a, y);
  long double res2 = s21_fmod(a, y);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(fmod_test_7) {
#line 608
  long double a = 1024.12;
  long double y = 3.146546;
  long double res1 = fmod(a, y);
  long double res2 = s21_fmod(a, y);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(fmod_test_8) {
#line 615
  long double a = -123456789;
  long double y = 5.99992;
  long double res1 = fmod(a, y);
  long double res2 = s21_fmod(a, y);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(fmod_test_9) {
#line 622
  long double a = -123456789;
  long double res2 = s21_fmod(a, S21_NEG_INF);
  ck_assert_ldouble_nan(res2);
}
END_TEST

START_TEST(fmod_test_10) {
#line 627
  long double a = -123456789;
  long double res2 = s21_fmod(S21_NAN, a);
  ck_assert_ldouble_nan(res2);
}
END_TEST

START_TEST(fmod_test_11) {
#line 632
  long double a = 6343789;
  long double y = -5.99992;
  long double res1 = fmod(a, y);
  long double res2 = s21_fmod(a, y);
  ck_assert_ldouble_eq_tol(res1, res2, 6);

  /*--------FMOD-TEST-END-----------------------------------------*/

  /*--------ATAN-TEST-START-----------------------------------------*/
}
END_TEST

START_TEST(atan_test_1) {
#line 644
  long double a = 4.122232134343;
  long double res1 = atan(a);
  long double res2 = s21_atan(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(atan_test_2) {
#line 650
  long double a = -4.345532335343;
  long double res1 = atan(a);
  long double res2 = s21_atan(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(atan_test_3) {
#line 656
  long double a = +0.234343433;
  long double res1 = atan(a);
  long double res2 = s21_atan(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(atan_test_4) {
#line 662
  long double a = -0.243232;
  long double res1 = atan(a);
  long double res2 = s21_atan(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(atan_test_5) {
#line 668
  long double a = 121212.123456789;
  long double res1 = atan(a);
  long double res2 = s21_atan(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(atan_test_6) {
#line 674
  long double a = -453.1024;
  long double res1 = atan(a);
  long double res2 = s21_atan(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(atan_test_7) {
#line 680
  long double a = 1024.12;
  long double res1 = atan(a);
  long double res2 = s21_atan(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(atan_test_8) {
#line 686
  long double a = -1234567.34343;
  long double res1 = atan(a);
  long double res2 = s21_atan(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(atan_test_9) {
#line 692
  long double a = 0.999934343;
  long double res1 = atan(a);
  long double res2 = s21_atan(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(atan_test_10) {
#line 698
  long double a = 0.111111111;
  long double res1 = atan(a);
  long double res2 = s21_atan(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(atan_test_11) {
#line 704
  long double a = 1;
  long double res1 = atan(a);
  long double res2 = s21_atan(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(atan_test_12) {
#line 710
  long double a = -1;
  long double res1 = atan(a);
  long double res2 = s21_atan(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(atan_test_13) {
#line 716
  long double a = S21_POS_INF;
  long double res1 = atan(a);
  long double res2 = s21_atan(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(atan_test_14) {
#line 722
  long double a = S21_NEG_INF;
  long double res1 = atan(a);
  long double res2 = s21_atan(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(atan_test_15) {
#line 728
  long double a = S21_NAN;
  long double res2 = s21_atan(a);
  ck_assert_ldouble_nan(res2);
  /*--------ATAN-TEST-END-----------------------------------------*/

  /*--------LOG-TEST-START-----------------------------------------*/
}
END_TEST

START_TEST(log_test_1) {
#line 736
  long double a = 4.122232134343;
  long double res1 = log(a);
  long double res2 = s21_log(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(log_test_2) {
#line 742
  long double a = -4.345532335343;
  long double res2 = s21_log(a);
  ck_assert_ldouble_nan(res2);
}
END_TEST

START_TEST(log_test_3) {
#line 747
  long double a = +0.234343433;
  long double res1 = log(a);
  long double res2 = s21_log(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(log_test_4) {
#line 753
  long double a = -0.243232;
  long double res2 = s21_log(a);
  ck_assert_ldouble_nan(res2);
}
END_TEST

START_TEST(log_test_5) {
#line 758
  long double a = 121212.123456789;
  long double res1 = log(a);
  long double res2 = s21_log(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(log_test_6) {
#line 764
  long double a = -453.1024;
  long double res2 = s21_log(a);
  ck_assert_ldouble_nan(res2);
}
END_TEST

START_TEST(log_test_7) {
#line 769
  long double a = 1024.12;
  long double res1 = log(a);
  long double res2 = s21_log(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(log_test_8) {
#line 775
  long double a = 123456789;
  long double res1 = log(a);
  long double res2 = s21_log(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(log_test_9) {
#line 781
  long double a = 0.111111111111;
  long double res1 = log(a);
  long double res2 = s21_log(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(log_test_10) {
#line 787
  long double a = 0.9999999;
  long double res1 = log(a);
  long double res2 = s21_log(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(log_test_11) {
#line 794
  long double res2 = s21_log(S21_NAN);
  ck_assert_ldouble_nan(res2);
}
END_TEST

START_TEST(log_test_12) {
#line 798
  long double res2 = s21_log(S21_POS_INF);
  ck_assert_ldouble_infinite(res2);
}
END_TEST

START_TEST(log_test_13) {
#line 802
  long double a = 0.;
  long double res2 = s21_log(a);
  ck_assert_ldouble_infinite(res2);

  /*--------LOG-TEST-END-----------------------------------------*/

  /*13--------SQRT-TEST-START--------------------------------------*/
}
END_TEST

START_TEST(sqrt_test_1) {
#line 811
  long double a = 0.0;
  long double res1 = sqrt(a);
  long double res2 = s21_sqrt(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(sqrt_test_2) {
#line 817
  long double a = 1.0;
  long double res1 = sqrt(a);
  long double res2 = s21_sqrt(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(sqrt_test_3) {
#line 823
  long double a = -1.0;
  long double res2 = s21_sqrt(a);
  ck_assert_ldouble_nan(res2);
}
END_TEST

START_TEST(sqrt_test_4) {
#line 828
  long double a = 0.5;
  long double res1 = sqrt(a);
  long double res2 = s21_sqrt(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(sqrt_test_5) {
#line 834
  long double a = S21_NAN;
  long double res2 = s21_sqrt(a);
  ck_assert_ldouble_nan(res2);
}
END_TEST

START_TEST(sqrt_test_6) {
#line 839
  long double a = S21_POS_INF;
  long double res2 = s21_sqrt(a);
  ck_assert_ldouble_infinite(res2);
}
END_TEST

START_TEST(sqrt_test_7) {
#line 844
  long double a = S21_NEG_INF;
  long double res2 = s21_sqrt(a);
  ck_assert_ldouble_nan(res2);
}
END_TEST

START_TEST(sqrt_test_8) {
#line 849
  long double a = -123456789;
  long double res2 = s21_sqrt(a);
  ck_assert_ldouble_nan(res2);

  /*13--------SQRT-TEST-END----------------------------------------*/

  /*14--------TAN-TEST-START--------------------------------------*/
}
END_TEST

START_TEST(tan_test_1) {
#line 858
  long double a = 0.0;
  long double res1 = tan(a);
  long double res2 = s21_tan(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(tan_test_2) {
#line 864
  long double a = 1.0;
  long double res1 = tan(a);
  long double res2 = s21_tan(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(tan_test_3) {
#line 870
  long double a = -1.0;
  long double res1 = tan(a);
  long double res2 = s21_tan(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(tan_test_4) {
#line 876
  long double a = 0.5;
  long double res1 = tan(a);
  long double res2 = s21_tan(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(tan_test_5) {
#line 882
  long double a = S21_NAN;
  long double res2 = s21_tan(a);
  ck_assert_ldouble_nan(res2);
}
END_TEST

START_TEST(tan_test_6) {
#line 887
  long double a = S21_POS_INF;
  long double res2 = s21_tan(a);
  ck_assert_ldouble_infinite(res2);
}
END_TEST

START_TEST(tan_test_7) {
#line 892
  long double a = S21_NEG_INF;
  long double res2 = s21_tan(a);
  ck_assert_ldouble_infinite(res2);
}
END_TEST

START_TEST(tan_test_8) {
#line 897
  long double a = -123456789;
  long double res1 = tan(a);
  long double res2 = s21_tan(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);

  /*14--------TAN-TEST-END----------------------------------------*/

  /*15--------ASIN-TEST-START--------------------------------------*/
}
END_TEST

START_TEST(asin_test_1) {
#line 907
  long double a = 0.0;
  long double res1 = asin(a);
  long double res2 = s21_asin(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(asin_test_2) {
#line 913
  long double a = 1.0;
  long double res1 = asin(a);
  long double res2 = s21_asin(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(asin_test_3) {
#line 919
  long double a = -1.0;
  long double res2 = s21_asin(a);
  long double res1 = asin(a);
  ck_assert_ldouble_eq_tol(res2, res1, 6);
}
END_TEST

START_TEST(asin_test_4) {
#line 925
  long double a = 0.5;
  long double res1 = asin(a);
  long double res2 = s21_asin(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);
}
END_TEST

START_TEST(asin_test_5) {
#line 931
  long double a = S21_NAN;
  long double res2 = s21_asin(a);
  ck_assert_ldouble_nan(res2);
}
END_TEST

START_TEST(asin_test_6) {
#line 936
  long double a = S21_POS_INF;
  long double res2 = s21_asin(a);
  ck_assert_ldouble_infinite(res2);
}
END_TEST

START_TEST(asin_test_7) {
#line 941
  long double a = S21_NEG_INF;
  long double res2 = s21_asin(a);
  ck_assert_ldouble_infinite(res2);
}
END_TEST

START_TEST(asin_test_8) {
#line 946
  long double a = -123456789;
  long double res1 = tan(a);
  long double res2 = s21_tan(a);
  ck_assert_ldouble_eq_tol(res1, res2, 6);

  /*15--------ASIN-TEST-END----------------------------------------*/
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, exp_test_1);
  tcase_add_test(tc1_1, exp_test_2);
  tcase_add_test(tc1_1, exp_test_3);
  tcase_add_test(tc1_1, exp_test_4);
  tcase_add_test(tc1_1, exp_test_5);
  tcase_add_test(tc1_1, exp_test_6);
  tcase_add_test(tc1_1, exp_test_7);
  tcase_add_test(tc1_1, exp_test_8);
  tcase_add_test(tc1_1, acos_test_1);
  tcase_add_test(tc1_1, acos_test_2);
  tcase_add_test(tc1_1, acos_test_3);
  tcase_add_test(tc1_1, acos_test_4);
  tcase_add_test(tc1_1, acos_test_5);
  tcase_add_test(tc1_1, acos_test_6);
  tcase_add_test(tc1_1, acos_test_7);
  tcase_add_test(tc1_1, acos_test_8);
  tcase_add_test(tc1_1, acos_test_9);
  tcase_add_test(tc1_1, acos_test_10);
  tcase_add_test(tc1_1, acos_test_11);
  tcase_add_test(tc1_1, acos_test_12);
  tcase_add_test(tc1_1, acos_test_13);
  tcase_add_test(tc1_1, acos_test_14);
  tcase_add_test(tc1_1, pow_test_1);
  tcase_add_test(tc1_1, pow_test_2);
  tcase_add_test(tc1_1, pow_test_3);
  tcase_add_test(tc1_1, pow_test_4);
  tcase_add_test(tc1_1, pow_test_5);
  tcase_add_test(tc1_1, pow_test_6);
  tcase_add_test(tc1_1, pow_test_7);
  tcase_add_test(tc1_1, pow_test_8);
  tcase_add_test(tc1_1, pow_test_9);
  tcase_add_test(tc1_1, pow_test_10);
  tcase_add_test(tc1_1, pow_test_11);
  tcase_add_test(tc1_1, abs_test_1);
  tcase_add_test(tc1_1, abs_test_2);
  tcase_add_test(tc1_1, abs_test_3);
  tcase_add_test(tc1_1, abs_test_4);
  tcase_add_test(tc1_1, abs_test_5);
  tcase_add_test(tc1_1, abs_test_6);
  tcase_add_test(tc1_1, abs_test_7);
  tcase_add_test(tc1_1, abs_test_8);
  tcase_add_test(tc1_1, floor_test_1);
  tcase_add_test(tc1_1, floor_test_2);
  tcase_add_test(tc1_1, floor_test_3);
  tcase_add_test(tc1_1, floor_test_4);
  tcase_add_test(tc1_1, floor_test_5);
  tcase_add_test(tc1_1, floor_test_6);
  tcase_add_test(tc1_1, floor_test_7);
  tcase_add_test(tc1_1, floor_test_8);
  tcase_add_test(tc1_1, fabs_test_1);
  tcase_add_test(tc1_1, fabs_test_2);
  tcase_add_test(tc1_1, fabs_test_3);
  tcase_add_test(tc1_1, fabs_test_4);
  tcase_add_test(tc1_1, fabs_test_5);
  tcase_add_test(tc1_1, fabs_test_6);
  tcase_add_test(tc1_1, fabs_test_7);
  tcase_add_test(tc1_1, fabs_test_8);
  tcase_add_test(tc1_1, ceil_test_1);
  tcase_add_test(tc1_1, ceil_test_2);
  tcase_add_test(tc1_1, ceil_test_3);
  tcase_add_test(tc1_1, ceil_test_4);
  tcase_add_test(tc1_1, ceil_test_5);
  tcase_add_test(tc1_1, ceil_test_6);
  tcase_add_test(tc1_1, ceil_test_7);
  tcase_add_test(tc1_1, ceil_test_8);
  tcase_add_test(tc1_1, ceil_test_9);
  tcase_add_test(tc1_1, ceil_test_10);
  tcase_add_test(tc1_1, sin_test_1);
  tcase_add_test(tc1_1, sin_test_2);
  tcase_add_test(tc1_1, sin_test_3);
  tcase_add_test(tc1_1, sin_test_4);
  tcase_add_test(tc1_1, sin_test_5);
  tcase_add_test(tc1_1, sin_test_6);
  tcase_add_test(tc1_1, sin_test_7);
  tcase_add_test(tc1_1, sin_test_8);
  tcase_add_test(tc1_1, sin_test_9);
  tcase_add_test(tc1_1, sin_test_10);
  tcase_add_test(tc1_1, sin_test_11);
  tcase_add_test(tc1_1, cos_test_1);
  tcase_add_test(tc1_1, cos_test_2);
  tcase_add_test(tc1_1, cos_test_3);
  tcase_add_test(tc1_1, cos_test_4);
  tcase_add_test(tc1_1, cos_test_5);
  tcase_add_test(tc1_1, cos_test_6);
  tcase_add_test(tc1_1, cos_test_7);
  tcase_add_test(tc1_1, cos_test_8);
  tcase_add_test(tc1_1, cos_test_9);
  tcase_add_test(tc1_1, cos_test_10);
  tcase_add_test(tc1_1, cos_test_11);
  tcase_add_test(tc1_1, cos_test_12);
  tcase_add_test(tc1_1, fmod_test_1);
  tcase_add_test(tc1_1, fmod_test_2);
  tcase_add_test(tc1_1, fmod_test_3);
  tcase_add_test(tc1_1, fmod_test_4);
  tcase_add_test(tc1_1, fmod_test_5);
  tcase_add_test(tc1_1, fmod_test_6);
  tcase_add_test(tc1_1, fmod_test_7);
  tcase_add_test(tc1_1, fmod_test_8);
  tcase_add_test(tc1_1, fmod_test_9);
  tcase_add_test(tc1_1, fmod_test_10);
  tcase_add_test(tc1_1, fmod_test_11);
  tcase_add_test(tc1_1, atan_test_1);
  tcase_add_test(tc1_1, atan_test_2);
  tcase_add_test(tc1_1, atan_test_3);
  tcase_add_test(tc1_1, atan_test_4);
  tcase_add_test(tc1_1, atan_test_5);
  tcase_add_test(tc1_1, atan_test_6);
  tcase_add_test(tc1_1, atan_test_7);
  tcase_add_test(tc1_1, atan_test_8);
  tcase_add_test(tc1_1, atan_test_9);
  tcase_add_test(tc1_1, atan_test_10);
  tcase_add_test(tc1_1, atan_test_11);
  tcase_add_test(tc1_1, atan_test_12);
  tcase_add_test(tc1_1, atan_test_13);
  tcase_add_test(tc1_1, atan_test_14);
  tcase_add_test(tc1_1, atan_test_15);
  tcase_add_test(tc1_1, log_test_1);
  tcase_add_test(tc1_1, log_test_2);
  tcase_add_test(tc1_1, log_test_3);
  tcase_add_test(tc1_1, log_test_4);
  tcase_add_test(tc1_1, log_test_5);
  tcase_add_test(tc1_1, log_test_6);
  tcase_add_test(tc1_1, log_test_7);
  tcase_add_test(tc1_1, log_test_8);
  tcase_add_test(tc1_1, log_test_9);
  tcase_add_test(tc1_1, log_test_10);
  tcase_add_test(tc1_1, log_test_11);
  tcase_add_test(tc1_1, log_test_12);
  tcase_add_test(tc1_1, log_test_13);
  tcase_add_test(tc1_1, sqrt_test_1);
  tcase_add_test(tc1_1, sqrt_test_2);
  tcase_add_test(tc1_1, sqrt_test_3);
  tcase_add_test(tc1_1, sqrt_test_4);
  tcase_add_test(tc1_1, sqrt_test_5);
  tcase_add_test(tc1_1, sqrt_test_6);
  tcase_add_test(tc1_1, sqrt_test_7);
  tcase_add_test(tc1_1, sqrt_test_8);
  tcase_add_test(tc1_1, tan_test_1);
  tcase_add_test(tc1_1, tan_test_2);
  tcase_add_test(tc1_1, tan_test_3);
  tcase_add_test(tc1_1, tan_test_4);
  tcase_add_test(tc1_1, tan_test_5);
  tcase_add_test(tc1_1, tan_test_6);
  tcase_add_test(tc1_1, tan_test_7);
  tcase_add_test(tc1_1, tan_test_8);
  tcase_add_test(tc1_1, asin_test_1);
  tcase_add_test(tc1_1, asin_test_2);
  tcase_add_test(tc1_1, asin_test_3);
  tcase_add_test(tc1_1, asin_test_4);
  tcase_add_test(tc1_1, asin_test_5);
  tcase_add_test(tc1_1, asin_test_6);
  tcase_add_test(tc1_1, asin_test_7);
  tcase_add_test(tc1_1, asin_test_8);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
