\input texinfo
@setfilename 3DViewer.info


@settitle 3DViewer

@node Top
@top Инструкция для 3DViewer

@strong{3DViewer }@*

@strong{Основные функции 3DViewer включают: }@*

@itemize
@item
Отображение 3D моделей: Позволяет просматривать трехмерные модели на экране;
@item
Вращение: Функция, позволяющая вращать модель вокруг осей X, Y и Z;
@item
Масштабирование: Функция для изменения размера модели;
@item
Панорамирование: Возможность перемещения модели по экрану;
@end itemize

@strong{Отображение информации о модели: }@*

@itemize
@item
Отображение статистики: Показывает информацию о модели, такую как количество вершин, граней и другие характеристики;
@end itemize

@bye
