/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "text_test/test_int_to_decimal.txt" instead.
 */

#include <check.h>

#include "../s21_decimal.h"
#include "test.h"

#line 1
START_TEST(s21_from_int_to_decimal1) {
#line 2

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = 2;

  res.bits[0] = 0b00000000000000000000000000000010;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b00000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal2) {
#line 19

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = -2;

  res.bits[0] = 0b00000000000000000000000000000010;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b10000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal3) {
#line 36

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = 2;

  res.bits[0] = 0b00000000000000000000000000000010;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b00000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal4) {
#line 53

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = -2;

  res.bits[0] = 0b00000000000000000000000000000010;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b10000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal5) {
#line 70

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = 3;

  res.bits[0] = 0b00000000000000000000000000000011;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b00000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal6) {
#line 87

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = -3;

  res.bits[0] = 0b00000000000000000000000000000011;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b10000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal7) {
#line 104

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = 3;

  res.bits[0] = 0b00000000000000000000000000000011;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b00000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal8) {
#line 121

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = -3;

  res.bits[0] = 0b00000000000000000000000000000011;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b10000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal9) {
#line 138

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = 3;

  res.bits[0] = 0b00000000000000000000000000000011;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b00000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal10) {
#line 155

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = -3;

  res.bits[0] = 0b00000000000000000000000000000011;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b10000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal11) {
#line 172

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = 3;

  res.bits[0] = 0b00000000000000000000000000000011;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b00000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal12) {
#line 189

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = -3;

  res.bits[0] = 0b00000000000000000000000000000011;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b10000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal13) {
#line 206

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = 0;

  res.bits[0] = 0b00000000000000000000000000000000;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b00000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal14) {
#line 223

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = 0;

  res.bits[0] = 0b00000000000000000000000000000000;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b00000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal15) {
#line 240

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = 3;

  res.bits[0] = 0b00000000000000000000000000000011;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b00000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal16) {
#line 257

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = -3;

  res.bits[0] = 0b00000000000000000000000000000011;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b10000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal17) {
#line 274

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = -3;

  res.bits[0] = 0b00000000000000000000000000000011;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b10000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal18) {
#line 291

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = 3;

  res.bits[0] = 0b00000000000000000000000000000011;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b00000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal19) {
#line 308

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = 1234567;

  res.bits[0] = 0b00000000000100101101011010000111;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b00000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal20) {
#line 325

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = -1234567;

  res.bits[0] = 0b00000000000100101101011010000111;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b10000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal21) {
#line 342

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = 1234567;

  res.bits[0] = 0b00000000000100101101011010000111;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b00000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal22) {
#line 359

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = -123456;

  res.bits[0] = 0b00000000000000011110001001000000;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b10000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal23) {
#line 376

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = 79228162;

  res.bits[0] = 0b00000100101110001110110100000010;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b00000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal24) {
#line 393

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = -79625142;

  res.bits[0] = 0b00000100101111101111101110110110;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b10000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal25) {
#line 410

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = -79228134;

  res.bits[0] = 0b00000100101110001110110011100110;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b10000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal26) {
#line 427

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = 79593334;

  res.bits[0] = 0b00000100101111100111111101110110;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b00000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal27) {
#line 444

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = 79228395;

  res.bits[0] = 0b00000100101110001110110111101011;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b00000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal28) {
#line 461

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = 66546445;

  res.bits[0] = 0b00000011111101110110101100001101;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b00000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal29) {
#line 478

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = 23126397;

  res.bits[0] = 0b00000001011000001110000101111101;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b00000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal30) {
#line 495

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = -979896154;

  res.bits[0] = 0b00111010011010000000011101011010;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b10000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal31) {
#line 512

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = 45646565;

  res.bits[0] = 0b00000010101110001000001011100101;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b00000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal32) {
#line 529

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = -454545781;

  res.bits[0] = 0b00011011000101111101000101110101;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b10000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal33) {
#line 546

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = -754390334;

  res.bits[0] = 0b00101100111101110001010100111110;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b10000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal34) {
#line 563

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = 323234854;

  res.bits[0] = 0b00010011010001000010110000100110;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b00000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal35) {
#line 580

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = -78452154;

  res.bits[0] = 0b00000100101011010001010110111010;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b10000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal36) {
#line 597

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = 0;

  res.bits[0] = 0b00000000000000000000000000000000;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b00000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal37) {
#line 614

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = 1;

  res.bits[0] = 0b00000000000000000000000000000001;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b00000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal38) {
#line 631

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = -1;

  res.bits[0] = 0b00000000000000000000000000000001;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b10000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal39) {
#line 648

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = 1;

  res.bits[0] = 0b00000000000000000000000000000001;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b00000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal40) {
#line 665

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = -1;

  res.bits[0] = 0b00000000000000000000000000000001;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b10000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal41) {
#line 682

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = 79225335;

  res.bits[0] = 0b00000100101110001110000111110111;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b00000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal42) {
#line 699

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = -79223950;

  res.bits[0] = 0b00000100101110001101110010001110;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b10000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal43) {
#line 716

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = 79859503;

  res.bits[0] = 0b00000100110000101000111100101111;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b00000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

START_TEST(s21_from_int_to_decimal44) {
#line 733

  int src1;
  s21_decimal res;
  s21_decimal our_res;

  src1 = -79225033;

  res.bits[0] = 0b00000100101110001110000011001001;
  res.bits[1] = 0b00000000000000000000000000000000;
  res.bits[2] = 0b00000000000000000000000000000000;
  res.bits[3] = 0b10000000000000000000000000000000;

  s21_from_int_to_decimal(src1, &our_res);

  ck_assert_int_eq(s21_is_equal(res, our_res), 1);
}
END_TEST

Suite *s21_s21_from_int_to_decimal(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, s21_from_int_to_decimal1);
  tcase_add_test(tc1_1, s21_from_int_to_decimal2);
  tcase_add_test(tc1_1, s21_from_int_to_decimal3);
  tcase_add_test(tc1_1, s21_from_int_to_decimal4);
  tcase_add_test(tc1_1, s21_from_int_to_decimal5);
  tcase_add_test(tc1_1, s21_from_int_to_decimal6);
  tcase_add_test(tc1_1, s21_from_int_to_decimal7);
  tcase_add_test(tc1_1, s21_from_int_to_decimal8);
  tcase_add_test(tc1_1, s21_from_int_to_decimal9);
  tcase_add_test(tc1_1, s21_from_int_to_decimal10);
  tcase_add_test(tc1_1, s21_from_int_to_decimal11);
  tcase_add_test(tc1_1, s21_from_int_to_decimal12);
  tcase_add_test(tc1_1, s21_from_int_to_decimal13);
  tcase_add_test(tc1_1, s21_from_int_to_decimal14);
  tcase_add_test(tc1_1, s21_from_int_to_decimal15);
  tcase_add_test(tc1_1, s21_from_int_to_decimal16);
  tcase_add_test(tc1_1, s21_from_int_to_decimal17);
  tcase_add_test(tc1_1, s21_from_int_to_decimal18);
  tcase_add_test(tc1_1, s21_from_int_to_decimal19);
  tcase_add_test(tc1_1, s21_from_int_to_decimal20);
  tcase_add_test(tc1_1, s21_from_int_to_decimal21);
  tcase_add_test(tc1_1, s21_from_int_to_decimal22);
  tcase_add_test(tc1_1, s21_from_int_to_decimal23);
  tcase_add_test(tc1_1, s21_from_int_to_decimal24);
  tcase_add_test(tc1_1, s21_from_int_to_decimal25);
  tcase_add_test(tc1_1, s21_from_int_to_decimal26);
  tcase_add_test(tc1_1, s21_from_int_to_decimal27);
  tcase_add_test(tc1_1, s21_from_int_to_decimal28);
  tcase_add_test(tc1_1, s21_from_int_to_decimal29);
  tcase_add_test(tc1_1, s21_from_int_to_decimal30);
  tcase_add_test(tc1_1, s21_from_int_to_decimal31);
  tcase_add_test(tc1_1, s21_from_int_to_decimal32);
  tcase_add_test(tc1_1, s21_from_int_to_decimal33);
  tcase_add_test(tc1_1, s21_from_int_to_decimal34);
  tcase_add_test(tc1_1, s21_from_int_to_decimal35);
  tcase_add_test(tc1_1, s21_from_int_to_decimal36);
  tcase_add_test(tc1_1, s21_from_int_to_decimal37);
  tcase_add_test(tc1_1, s21_from_int_to_decimal38);
  tcase_add_test(tc1_1, s21_from_int_to_decimal39);
  tcase_add_test(tc1_1, s21_from_int_to_decimal40);
  tcase_add_test(tc1_1, s21_from_int_to_decimal41);
  tcase_add_test(tc1_1, s21_from_int_to_decimal42);
  tcase_add_test(tc1_1, s21_from_int_to_decimal43);
  tcase_add_test(tc1_1, s21_from_int_to_decimal44);

  return s1;
}
