/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "text_test/decimal_to_int.txt" instead.
 */

#include <check.h>
#include <stdio.h>

#include "../s21_decimal.h"
#include "test.h"

#line 1
START_TEST(s21_from_decimal_to_int1) {
#line 2

  s21_decimal src1;
  int res, our_res;

  // src1 = 2;

  src1.bits[0] = 0b00000000000000000000000000000010;
  src1.bits[1] = 0b00000000000000000000000000000000;
  src1.bits[2] = 0b00000000000000000000000000000000;
  src1.bits[3] = 0b00000000000000000000000000000000;

  res = 2;

  s21_from_decimal_to_int(src1, &our_res);

  ck_assert_int_eq(res, our_res);
}
END_TEST

START_TEST(s21_from_decimal_to_int2) {
#line 20

  s21_decimal src1;
  int res, our_res;

  // src1 = -2;

  src1.bits[0] = 0b00000000000000000000000000000010;
  src1.bits[1] = 0b00000000000000000000000000000000;
  src1.bits[2] = 0b00000000000000000000000000000000;
  src1.bits[3] = 0b10000000000000000000000000000000;

  res = -2;

  s21_from_decimal_to_int(src1, &our_res);

  ck_assert_int_eq(res, our_res);
}
END_TEST

START_TEST(s21_from_decimal_to_int3) {
#line 38

  s21_decimal src1;
  int res, our_res;

  // src1 = 2;

  src1.bits[0] = 0b00000000000000000000000000000010;
  src1.bits[1] = 0b00000000000000000000000000000000;
  src1.bits[2] = 0b00000000000000000000000000000000;
  src1.bits[3] = 0b00000000000000000000000000000000;

  res = 2;

  s21_from_decimal_to_int(src1, &our_res);

  ck_assert_int_eq(res, our_res);
}
END_TEST

START_TEST(s21_from_decimal_to_int4) {
#line 56

  s21_decimal src1;
  int res, our_res;

  // src1 = -2;

  src1.bits[0] = 0b00000000000000000000000000000010;
  src1.bits[1] = 0b00000000000000000000000000000000;
  src1.bits[2] = 0b00000000000000000000000000000000;
  src1.bits[3] = 0b10000000000000000000000000000000;

  res = -2;

  s21_from_decimal_to_int(src1, &our_res);

  ck_assert_int_eq(res, our_res);
}
END_TEST

START_TEST(s21_from_decimal_to_int5) {
#line 74

  s21_decimal src1;
  int res, our_res;

  // src1 = 3;

  src1.bits[0] = 0b00000000000000000000000000000011;
  src1.bits[1] = 0b00000000000000000000000000000000;
  src1.bits[2] = 0b00000000000000000000000000000000;
  src1.bits[3] = 0b00000000000000000000000000000000;

  res = 3;

  s21_from_decimal_to_int(src1, &our_res);

  ck_assert_int_eq(res, our_res);
}
END_TEST

START_TEST(s21_from_decimal_to_int6) {
#line 92

  s21_decimal src1;
  int res, our_res;

  // src1 = -3;

  src1.bits[0] = 0b00000000000000000000000000000011;
  src1.bits[1] = 0b00000000000000000000000000000000;
  src1.bits[2] = 0b00000000000000000000000000000000;
  src1.bits[3] = 0b10000000000000000000000000000000;

  res = -3;

  s21_from_decimal_to_int(src1, &our_res);

  ck_assert_int_eq(res, our_res);
}
END_TEST

START_TEST(s21_from_decimal_to_int7) {
#line 110

  s21_decimal src1;
  int res, our_res;

  // src1 = 3;

  src1.bits[0] = 0b00000000000000000000000000000011;
  src1.bits[1] = 0b00000000000000000000000000000000;
  src1.bits[2] = 0b00000000000000000000000000000000;
  src1.bits[3] = 0b00000000000000000000000000000000;

  res = 3;

  s21_from_decimal_to_int(src1, &our_res);

  ck_assert_int_eq(res, our_res);
}
END_TEST

START_TEST(s21_from_decimal_to_int8) {
#line 128

  s21_decimal src1;
  int res, our_res;

  // src1 = -3;

  src1.bits[0] = 0b00000000000000000000000000000011;
  src1.bits[1] = 0b00000000000000000000000000000000;
  src1.bits[2] = 0b00000000000000000000000000000000;
  src1.bits[3] = 0b10000000000000000000000000000000;

  res = -3;

  s21_from_decimal_to_int(src1, &our_res);

  ck_assert_int_eq(res, our_res);
}
END_TEST

START_TEST(s21_from_decimal_to_int9) {
#line 146

  s21_decimal src1;
  int res, our_res;

  // src1 = 3;

  src1.bits[0] = 0b00000000000000000000000000000011;
  src1.bits[1] = 0b00000000000000000000000000000000;
  src1.bits[2] = 0b00000000000000000000000000000000;
  src1.bits[3] = 0b00000000000000000000000000000000;

  res = 3;

  s21_from_decimal_to_int(src1, &our_res);

  ck_assert_int_eq(res, our_res);
}
END_TEST

START_TEST(s21_from_decimal_to_int10) {
#line 164

  s21_decimal src1;
  int res, our_res;

  // src1 = -3;

  src1.bits[0] = 0b00000000000000000000000000000011;
  src1.bits[1] = 0b00000000000000000000000000000000;
  src1.bits[2] = 0b00000000000000000000000000000000;
  src1.bits[3] = 0b10000000000000000000000000000000;

  res = -3;

  s21_from_decimal_to_int(src1, &our_res);

  ck_assert_int_eq(res, our_res);
}
END_TEST

START_TEST(s21_from_decimal_to_int11) {
#line 182

  s21_decimal src1;
  int res, our_res;

  // src1 = 3;

  src1.bits[0] = 0b00000000000000000000000000000011;
  src1.bits[1] = 0b00000000000000000000000000000000;
  src1.bits[2] = 0b00000000000000000000000000000000;
  src1.bits[3] = 0b00000000000000000000000000000000;

  res = 3;

  s21_from_decimal_to_int(src1, &our_res);

  ck_assert_int_eq(res, our_res);
}
END_TEST

START_TEST(s21_from_decimal_to_int12) {
#line 200

  s21_decimal src1;
  int res, our_res;

  // src1 = -3;

  src1.bits[0] = 0b00000000000000000000000000000011;
  src1.bits[1] = 0b00000000000000000000000000000000;
  src1.bits[2] = 0b00000000000000000000000000000000;
  src1.bits[3] = 0b10000000000000000000000000000000;

  res = -3;

  s21_from_decimal_to_int(src1, &our_res);

  ck_assert_int_eq(res, our_res);
}
END_TEST

START_TEST(s21_from_decimal_to_int13) {
#line 218

  s21_decimal src1;
  int res, our_res;

  // src1 = 0;

  src1.bits[0] = 0b00000000000000000000000000000000;
  src1.bits[1] = 0b00000000000000000000000000000000;
  src1.bits[2] = 0b00000000000000000000000000000000;
  src1.bits[3] = 0b00000000000000000000000000000000;

  res = 0;

  s21_from_decimal_to_int(src1, &our_res);

  ck_assert_int_eq(res, our_res);
}
END_TEST

START_TEST(s21_from_decimal_to_int14) {
#line 236

  s21_decimal src1;
  int res, our_res;

  // src1 = 0;

  src1.bits[0] = 0b00000000000000000000000000000000;
  src1.bits[1] = 0b00000000000000000000000000000000;
  src1.bits[2] = 0b00000000000000000000000000000000;
  src1.bits[3] = 0b00000000000000000000000000000000;

  res = 0;

  s21_from_decimal_to_int(src1, &our_res);

  ck_assert_int_eq(res, our_res);
}
END_TEST

START_TEST(s21_from_decimal_to_int15) {
#line 254

  s21_decimal src1;
  int res, our_res;

  // src1 = 3.2;

  src1.bits[0] = 0b00000000000000000000000000100000;
  src1.bits[1] = 0b00000000000000000000000000000000;
  src1.bits[2] = 0b00000000000000000000000000000000;
  src1.bits[3] = 0b00000000000000010000000000000000;

  res = 3;

  s21_from_decimal_to_int(src1, &our_res);

  ck_assert_int_eq(res, our_res);
}
END_TEST

START_TEST(s21_from_decimal_to_int16) {
#line 272

  s21_decimal src1;
  int res, our_res;

  // src1 = -3.2;

  src1.bits[0] = 0b00000000000000000000000000100000;
  src1.bits[1] = 0b00000000000000000000000000000000;
  src1.bits[2] = 0b00000000000000000000000000000000;
  src1.bits[3] = 0b10000000000000010000000000000000;

  res = -3;

  s21_from_decimal_to_int(src1, &our_res);

  ck_assert_int_eq(res, our_res);
}
END_TEST

START_TEST(s21_from_decimal_to_int17) {
#line 290

  s21_decimal src1;
  int res, our_res;

  // src1 = -3.2;

  src1.bits[0] = 0b00000000000000000000000000100000;
  src1.bits[1] = 0b00000000000000000000000000000000;
  src1.bits[2] = 0b00000000000000000000000000000000;
  src1.bits[3] = 0b10000000000000010000000000000000;

  res = -3;

  s21_from_decimal_to_int(src1, &our_res);

  ck_assert_int_eq(res, our_res);
}
END_TEST

START_TEST(s21_from_decimal_to_int18) {
#line 308

  s21_decimal src1;
  int res, our_res;

  // src1 = 3.2;

  src1.bits[0] = 0b00000000000000000000000000100000;
  src1.bits[1] = 0b00000000000000000000000000000000;
  src1.bits[2] = 0b00000000000000000000000000000000;
  src1.bits[3] = 0b00000000000000010000000000000000;

  res = 3;

  s21_from_decimal_to_int(src1, &our_res);

  ck_assert_int_eq(res, our_res);
}
END_TEST

START_TEST(s21_from_decimal_to_int19) {
#line 326

  s21_decimal src1;
  int res, our_res;

  // src1 = 12345677.987654345678987654346;

  src1.bits[0] = 0b10010001000010101111010011001010;
  src1.bits[1] = 0b11000000010001011101010111110010;
  src1.bits[2] = 0b00100111111001000001101100000000;
  src1.bits[3] = 0b00000000000101010000000000000000;

  res = 12345677;

  s21_from_decimal_to_int(src1, &our_res);

  ck_assert_int_eq(res, our_res);
}
END_TEST

START_TEST(s21_from_decimal_to_int20) {
#line 344

  s21_decimal src1;
  int res, our_res;

  // src1 = -12345677.987654345678987654346;

  src1.bits[0] = 0b10010001000010101111010011001010;
  src1.bits[1] = 0b11000000010001011101010111110010;
  src1.bits[2] = 0b00100111111001000001101100000000;
  src1.bits[3] = 0b10000000000101010000000000000000;

  res = -12345677;

  s21_from_decimal_to_int(src1, &our_res);

  ck_assert_int_eq(res, our_res);
}
END_TEST

START_TEST(s21_from_decimal_to_int21) {
#line 362

  s21_decimal src1;
  int res, our_res;

  // src1 = 12345677.987654345678987654346;

  src1.bits[0] = 0b10010001000010101111010011001010;
  src1.bits[1] = 0b11000000010001011101010111110010;
  src1.bits[2] = 0b00100111111001000001101100000000;
  src1.bits[3] = 0b00000000000101010000000000000000;

  res = 12345677;

  s21_from_decimal_to_int(src1, &our_res);

  ck_assert_int_eq(res, our_res);
}
END_TEST

START_TEST(s21_from_decimal_to_int22) {
#line 380

  s21_decimal src1;
  int res, our_res;

  // src1 = -12345677.987654345678987654346;

  src1.bits[0] = 0b10010001000010101111010011001010;
  src1.bits[1] = 0b11000000010001011101010111110010;
  src1.bits[2] = 0b00100111111001000001101100000000;
  src1.bits[3] = 0b10000000000101010000000000000000;

  res = -12345677;

  s21_from_decimal_to_int(src1, &our_res);

  ck_assert_int_eq(res, our_res);
}
END_TEST

START_TEST(s21_from_decimal_to_int28) {
#line 398

  s21_decimal src1;
  int res, our_res;

  // src1 = 665464545;

  src1.bits[0] = 0b00100111101010100010111011100001;
  src1.bits[1] = 0b00000000000000000000000000000000;
  src1.bits[2] = 0b00000000000000000000000000000000;
  src1.bits[3] = 0b00000000000000000000000000000000;

  res = 665464545;

  s21_from_decimal_to_int(src1, &our_res);

  ck_assert_int_eq(res, our_res);
}
END_TEST

START_TEST(s21_from_decimal_to_int29) {
#line 416

  s21_decimal src1;
  int res, our_res;

  // src1 = 2.7986531268974139743;

  src1.bits[0] = 0b11111110100100001101100101011111;
  src1.bits[1] = 0b10000100011001000010000111101000;
  src1.bits[2] = 0b00000000000000000000000000000001;
  src1.bits[3] = 0b00000000000100110000000000000000;

  res = 2;

  s21_from_decimal_to_int(src1, &our_res);

  ck_assert_int_eq(res, our_res);
}
END_TEST

START_TEST(s21_from_decimal_to_int31) {
#line 434

  s21_decimal src1;
  int res, our_res;

  // src1 = 0.5456465465486476846545465485;

  src1.bits[0] = 0b00001011000011110111000010001101;
  src1.bits[1] = 0b10010110101100000101100101010001;
  src1.bits[2] = 0b00010001101000010111101110000001;
  src1.bits[3] = 0b00000000000111000000000000000000;

  res = 0;

  s21_from_decimal_to_int(src1, &our_res);

  ck_assert_int_eq(res, our_res);
}
END_TEST

START_TEST(s21_from_decimal_to_int32) {
#line 452

  s21_decimal src1;
  int res, our_res;

  // src1 = -0.77545545454546589781;

  src1.bits[0] = 0b10101100001010000001100001010101;
  src1.bits[1] = 0b00110100001010010001111010111100;
  src1.bits[2] = 0b00000000000000000000000000000100;
  src1.bits[3] = 0b10000000000101000000000000000000;

  res = 0;

  s21_from_decimal_to_int(src1, &our_res);

  ck_assert_int_eq(res, our_res);
}
END_TEST

START_TEST(s21_from_decimal_to_int35) {
#line 470

  s21_decimal src1;
  int res, our_res;

  // src1 = -784515454.7989898652154545652;

  src1.bits[0] = 0b10110001001110110100010111110100;
  src1.bits[1] = 0b00111000100000111010110010000001;
  src1.bits[2] = 0b00011001010110010101110000011000;
  src1.bits[3] = 0b10000000000100110000000000000000;

  res = -784515454;

  s21_from_decimal_to_int(src1, &our_res);

  ck_assert_int_eq(res, our_res);
}
END_TEST

START_TEST(s21_from_decimal_to_int36) {
#line 488

  s21_decimal src1;
  int res, our_res;

  // src1 = 0;

  src1.bits[0] = 0b00000000000000000000000000000000;
  src1.bits[1] = 0b00000000000000000000000000000000;
  src1.bits[2] = 0b00000000000000000000000000000000;
  src1.bits[3] = 0b00000000000000000000000000000000;

  res = 0;

  s21_from_decimal_to_int(src1, &our_res);

  ck_assert_int_eq(res, our_res);
}
END_TEST

START_TEST(s21_from_decimal_to_int37) {
#line 506

  s21_decimal src1;
  int res, our_res;

  // src1 = 1.0;

  src1.bits[0] = 0b00000000000000000000000000001010;
  src1.bits[1] = 0b00000000000000000000000000000000;
  src1.bits[2] = 0b00000000000000000000000000000000;
  src1.bits[3] = 0b00000000000000010000000000000000;

  res = 1;

  s21_from_decimal_to_int(src1, &our_res);

  ck_assert_int_eq(res, our_res);
}
END_TEST

START_TEST(s21_from_decimal_to_int38) {
#line 524

  s21_decimal src1;
  int res, our_res;

  // src1 = -1.0;

  src1.bits[0] = 0b00000000000000000000000000001010;
  src1.bits[1] = 0b00000000000000000000000000000000;
  src1.bits[2] = 0b00000000000000000000000000000000;
  src1.bits[3] = 0b10000000000000010000000000000000;

  res = -1;

  s21_from_decimal_to_int(src1, &our_res);

  ck_assert_int_eq(res, our_res);
}
END_TEST

START_TEST(s21_from_decimal_to_int39) {
#line 542

  s21_decimal src1;
  int res, our_res;

  // src1 = 1.0;

  src1.bits[0] = 0b00000000000000000000000000001010;
  src1.bits[1] = 0b00000000000000000000000000000000;
  src1.bits[2] = 0b00000000000000000000000000000000;
  src1.bits[3] = 0b00000000000000010000000000000000;

  res = 1;

  s21_from_decimal_to_int(src1, &our_res);

  ck_assert_int_eq(res, our_res);
}
END_TEST

START_TEST(s21_from_decimal_to_int40) {
#line 560

  s21_decimal src1;
  int res, our_res;

  // src1 = -1.0;

  src1.bits[0] = 0b00000000000000000000000000001010;
  src1.bits[1] = 0b00000000000000000000000000000000;
  src1.bits[2] = 0b00000000000000000000000000000000;
  src1.bits[3] = 0b10000000000000010000000000000000;

  res = -1;

  s21_from_decimal_to_int(src1, &our_res);

  ck_assert_int_eq(res, our_res);
}
END_TEST

START_TEST(s21_from_decimal_to_int45) {
#line 578

  s21_decimal src1;
  int res, our_res;

  // src1 = 0.0000000000000000000002;

  src1.bits[0] = 0b00000000000000000000000000000010;
  src1.bits[1] = 0b00000000000000000000000000000000;
  src1.bits[2] = 0b00000000000000000000000000000000;
  src1.bits[3] = 0b00000000000101100000000000000000;

  res = 0;

  s21_from_decimal_to_int(src1, &our_res);

  ck_assert_int_eq(res, our_res);
}
END_TEST

START_TEST(s21_from_decimal_to_int46) {
#line 596

  s21_decimal src1;
  int res, our_res;

  // src1 = -0.0000000000000000000002;

  src1.bits[0] = 0b00000000000000000000000000000010;
  src1.bits[1] = 0b00000000000000000000000000000000;
  src1.bits[2] = 0b00000000000000000000000000000000;
  src1.bits[3] = 0b10000000000101100000000000000000;

  res = 0;

  s21_from_decimal_to_int(src1, &our_res);

  ck_assert_int_eq(res, our_res);
}
END_TEST

START_TEST(s21_from_decimal_to_int47) {
#line 614

  s21_decimal src1;
  int res, our_res;

  // src1 = 0.0000000000000000000002;

  src1.bits[0] = 0b00000000000000000000000000000010;
  src1.bits[1] = 0b00000000000000000000000000000000;
  src1.bits[2] = 0b00000000000000000000000000000000;
  src1.bits[3] = 0b00000000000101100000000000000000;

  res = 0;

  s21_from_decimal_to_int(src1, &our_res);

  ck_assert_int_eq(res, our_res);
}
END_TEST

START_TEST(s21_from_decimal_to_int48) {
#line 632

  s21_decimal src1;
  int res, our_res;

  // src1 = 0.0000000000000000000002;

  src1.bits[0] = 0b00000000000000000000000000000010;
  src1.bits[1] = 0b00000000000000000000000000000000;
  src1.bits[2] = 0b00000000000000000000000000000000;
  src1.bits[3] = 0b00000000000101100000000000000000;

  res = 0;

  s21_from_decimal_to_int(src1, &our_res);

  ck_assert_int_eq(res, our_res);
}
END_TEST

Suite *s21_s21_from_decimal_to_int(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, s21_from_decimal_to_int1);
  tcase_add_test(tc1_1, s21_from_decimal_to_int2);
  tcase_add_test(tc1_1, s21_from_decimal_to_int3);
  tcase_add_test(tc1_1, s21_from_decimal_to_int4);
  tcase_add_test(tc1_1, s21_from_decimal_to_int5);
  tcase_add_test(tc1_1, s21_from_decimal_to_int6);
  tcase_add_test(tc1_1, s21_from_decimal_to_int7);
  tcase_add_test(tc1_1, s21_from_decimal_to_int8);
  tcase_add_test(tc1_1, s21_from_decimal_to_int9);
  tcase_add_test(tc1_1, s21_from_decimal_to_int10);
  tcase_add_test(tc1_1, s21_from_decimal_to_int11);
  tcase_add_test(tc1_1, s21_from_decimal_to_int12);
  tcase_add_test(tc1_1, s21_from_decimal_to_int13);
  tcase_add_test(tc1_1, s21_from_decimal_to_int14);
  tcase_add_test(tc1_1, s21_from_decimal_to_int15);
  tcase_add_test(tc1_1, s21_from_decimal_to_int16);
  tcase_add_test(tc1_1, s21_from_decimal_to_int17);
  tcase_add_test(tc1_1, s21_from_decimal_to_int18);
  tcase_add_test(tc1_1, s21_from_decimal_to_int19);
  tcase_add_test(tc1_1, s21_from_decimal_to_int20);
  tcase_add_test(tc1_1, s21_from_decimal_to_int21);
  tcase_add_test(tc1_1, s21_from_decimal_to_int22);
  tcase_add_test(tc1_1, s21_from_decimal_to_int28);
  tcase_add_test(tc1_1, s21_from_decimal_to_int29);
  tcase_add_test(tc1_1, s21_from_decimal_to_int31);
  tcase_add_test(tc1_1, s21_from_decimal_to_int32);
  tcase_add_test(tc1_1, s21_from_decimal_to_int35);
  tcase_add_test(tc1_1, s21_from_decimal_to_int36);
  tcase_add_test(tc1_1, s21_from_decimal_to_int37);
  tcase_add_test(tc1_1, s21_from_decimal_to_int38);
  tcase_add_test(tc1_1, s21_from_decimal_to_int39);
  tcase_add_test(tc1_1, s21_from_decimal_to_int40);
  tcase_add_test(tc1_1, s21_from_decimal_to_int45);
  tcase_add_test(tc1_1, s21_from_decimal_to_int46);
  tcase_add_test(tc1_1, s21_from_decimal_to_int47);
  tcase_add_test(tc1_1, s21_from_decimal_to_int48);

  return s1;
}
